// <auto-generated />
using System;
using ArabicSchoolArchive.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArabicSchoolArchive.Api.Data.Migrations
{
    [DbContext(typeof(ArchiveDbContext))]
    [Migration("20260617022722_AddN8nRichMetadata")]
    partial class AddN8nRichMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArabicSchoolArchive.Api.Entities.Archive", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<string>("BlobObjectName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("blob_object_name");

                    b.Property<string>("Category")
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)")
                        .HasColumnName("category");

                    b.Property<double?>("Confidence")
                        .HasColumnType("float")
                        .HasColumnName("confidence");

                    b.Property<string>("ContentHashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("content_hash_sha256");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("display_name");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)")
                        .HasColumnName("mime_type");

                    b.Property<bool>("NeedsReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("needs_review");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("original_name");

                    b.Property<byte>("ProcessingMonth")
                        .HasColumnType("tinyint")
                        .HasColumnName("processing_month");

                    b.Property<int>("ProcessingYear")
                        .HasColumnType("int")
                        .HasColumnName("processing_year");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("safe_name");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("school_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Summary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("summary");

                    b.Property<string>("TagsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags_json");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("DocumentId");

                    b.HasIndex("SchoolId", "DisplayName")
                        .HasDatabaseName("IX_Archives_School_DisplayName");

                    b.HasIndex("SchoolId", "OriginalName")
                        .HasDatabaseName("IX_Archives_School_OriginalName");

                    b.HasIndex("SchoolId", "Summary")
                        .HasDatabaseName("IX_Archives_School_Summary");

                    b.HasIndex("SchoolId", "UploadedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Archives_School_UploadedAt");

                    b.HasIndex("SchoolId", "Category", "UploadedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Archives_School_Category");

                    b.ToTable("Archives", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
